### ISSUE TITLE
About permission

### ISSUE THREAD

**Issue by empty814** [chengxuxin/extreme-parkour#14]
hi, do i need some permission about your project?
when i run " python train.py --exptid quadrupedal-locomotion --device cuda:0"
i got the follow message:
Importing module 'gym_38' (/home/xyb/lhz/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/xyb/lhz/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/home/xyb/lhz/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/xyb/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /home/xyb/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
wandb: Currently logged in as: 1710730875. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
Problem at: train.py 62 train
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    train(args)
  File "train.py", line 62, in train
    wandb.init(project=args.proj_name, name=args.exptid, entity="parkour", group=args.exptid[:3], mode=mode, dir="../../logs")
  File "/home/xyb/anaconda3/envs/parkour/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    raise e
  File "/home/xyb/anaconda3/envs/parkour/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    run = wi.init()
  File "/home/xyb/anaconda3/envs/parkour/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)

**Comment by chengxuxin** [comment]
Looks like wandb login error. Please execute wandb login --relogin before running the commands. Or simply disable wandb by adding argument —no_wandb.
