### ISSUE TITLE
base policy terrain level

### ISSUE THREAD

**Issue by drewjenks01** [chengxuxin/extreme-parkour#15]
Hi, when training the base policy, what did the terrain level progression look like over 20k training iterations? From the code, it looks like the max level is 10, but my policy is only reaching level 6 and then mostly leveling out (see below)
<img width="521" alt="image" src="https://github.com/chengxuxin/extreme-parkour/assets/71949964/befbf54e-c040-423d-8968-c0739e42c5b1">

**Comment by chengxuxin** [comment]
It is normal since those having reached max terrain will be redistributed uniformly to all terrain levels.
