### ISSUE TITLE
how many envs do you use when running the train.py?

### ISSUE THREAD

**Issue by shitoujie** [chengxuxin/extreme-parkour#18]
As you mentioned in READ.md: 

`Train 10-15k iterations (8-10 hours on 3090) (at least 15k recommended).`
so, when you train 10-15k iterations,what's the number of envs?
it seems like i can only run the train.py with 50 envs on my 3080 (in the headless mode).
I'm looking fowrward to your reply.

**Comment by tenhearts** [comment]
For phase 1: 4096 envs. For Phase 2: 128 envs.

**Comment by 1242713693** [comment]
Hello, have you built your simulation environment successfully? Can you take a look at the graphical interface after your simulation! thank you.
