### ISSUE TITLE
I attempted to install the `legged-gym` package from this repository using the command `pip install -e .` within the `legged_gym` folder. However, I encountered a dependency conflict and missing dependencies during the installation process.

### ISSUE THREAD

**Issue by shashankyld** [chengxuxin/extreme-parkour#3]
Installing collected packages: zipp, six, pyparsing, packaging, kiwisolver, fonttools, cycler, contourpy, matplotlib, legged-gym
Running setup.py develop for legged-gym
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```
bleach 6.0.0 requires webencodings, which is not installed.
ipykernel 6.25.0 requires psutil, which is not installed.
nbconvert 7.7.3 requires beautifulsoup4, which is not installed.
nbconvert 7.7.3 requires defusedxml, which is not installed.
pytest 7.3.1 requires pluggy<2.0,>=0.12, which is not installed.
```

**Requested Action:**

I am reporting this issue to request that the maintainers of the `legged-gym` package modify their installation script to include the missing dependencies. This will help ensure a smoother installation process for users.

**Additional Information:**

- Operating System: Ubuntu 20

Please let me know if there is any further information needed to address this issue. Thank you!

**Comment by chengxuxin** [comment]
I have no problem with the installation scripts provided. Could you provide more details including the commands you ran on how you installed?
