### ISSUE TITLE
Failed to create a valid PhysX CUDA Context Manager. Falling back to CPU

### ISSUE THREAD

**Issue by lizhiwen19900709** [chengxuxin/extreme-parkour#4]
![image](https://github.com/chengxuxin/extreme-parkour/assets/15767823/d4f6b0a9-2a6a-439d-ad3b-7f68d9917d4b)

**Comment by chengxuxin** [comment]
Looks like a driver issue. Please try to upgrade nvidia driver.
Also see here:
[https://forums.developer.nvidia.com/t/failed-to-create-a-physx-cuda-context-manager-falling-back-to-cpu/173406/3](https://forums.developer.nvidia.com/t/failed-to-create-a-physx-cuda-context-manager-falling-back-to-cpu/173406/3)
