### ISSUE TITLE
hardware frequency

### ISSUE THREAD

**Issue by LiuYiKai6** [chengxuxin/extreme-parkour#6]
Thanks for your work! We are trying to deploy your policy on real go1 robot, but find the frequency so fast with dt=0.005 and decimation=4, may I ask the dt and decimation (may be other frequency parameters) you used on the hardware? thanks!

**Comment by KUsaka-xu** [comment]
@LiuYiKai6  have you deployed the policy into go1? if you can share the work, it helps me a lot
